name       : avahi
version    : 0.7
release    : 16
source     :
    - https://github.com/lathiat/avahi/releases/download/v0.7/avahi-0.7.tar.gz : 57a99b5dfe7fdae794e3d1ee7a62973a368e91e414bd0dfa5d84434de5b14804
license    : LGPL-2.1-or-later
component  : desktop.core
summary    : mDNS/DNS-SD service discovery
description: |
    Avahi is a system which facilitates service discovery on a local network via the mDNS/DNS-SD protocol suite. This enables you to plug your laptop or computer into a network and instantly be able to view other people who you can chat with, find printers to print to or find files being shared.
libsplit   : no
emul32     : yes
builddeps  :
    - pkgconfig32(dbus-1)
    - pkgconfig32(glib-2.0)
    - pkgconfig32(expat)
    - pkgconfig32(libdaemon)
    - pkgconfig32(liblzma)
    - gdbm-32bit-devel
    - libgcrypt-32bit-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-daemon-Ensure-system-is-online-before-starting-Avahi.patch
    %patch -p1 < $pkgfiles/0001-Fall-back-to-stateless-directory.patch
    %reconfigure --disable-static \
                 --disable-mono \
                 --disable-monodoc \
                 --disable-python \
                 --disable-qt3 \
                 --disable-qt4 \
                 --disable-gtk \
                 --disable-gtk3 \
                 --enable-compat-libdns_sd \
                 --enable-core-docs \
                 --with-avahi-priv-access-group=avahi \
                 --with-systemdsystemunitdir=%libdir%/systemd/system \
                 --with-distro=none
build      : |
    %make
install    : |
    %make_install
    rm -frv $installdir/run

    if [[ -z "${EMUL32BUILD}" ]]; then
        ln -s /usr/include/avahi-compat-libdns_sd/dns_sd.h $installdir/usr/include/dns_sd.h

        install -D -m 00644 $pkgfiles/avahi.sysusers $installdir%libdir%/sysusers.d/avahi.conf
        install -D -m 00644 $pkgfiles/avahi.tmpfiles $installdir%libdir%/tmpfiles.d/avahi.conf

        # Pre-enable socket
        install -D -d -m 00755 $installdir/%libdir%/systemd/system/sockets.target.wants
        ln -sv ../avahi-daemon.socket $installdir/%libdir%/systemd/system/sockets.target.wants/.

        # Pre-enable dbus activation
        ln -sv avahi-daemon.service $installdir/%libdir%/systemd/system/dbus-org.freedesktop.Avahi.service
    else
        rm -rf $installdir/%libdir%/systemd
    fi
    # Move files to stateless path
    install -dm00644 $installdir/usr/share/defaults
    mv $installdir/etc/avahi $installdir/usr/share/defaults/avahi
    # Fix dbus-1 location without changing sysconfdir, which would break our /etc lookups
    install -dm00644 $installdir/usr/share/dbus-1/system.d/
    mv $installdir/etc/dbus-1/system.d/avahi-dbus.conf $installdir/usr/share/dbus-1/system.d/
    # Can now nuke since all content is moved
    rm -rf $installdir/etc
